name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: git update-index --chmod=+x gradlew

      - name: Build EXE
        shell: cmd
        run: |
          gradlew.bat --no-daemon clean
          gradlew.bat --no-daemon packageReleaseExe

      - name: Debug â€“ List build folders
        shell: cmd
        run: |
          echo "Listing build folders..."
          dir build
          echo "------------------------------------"
          echo "Listing compose directory..."
          dir build\compose
          echo "------------------------------------"
          echo "Listing binaries directory recursively..."
          dir build\compose\binaries /s

      - name: Create config.properties
        run: |
          echo API_KEY=${{ secrets.API_KEY }} >> config.properties
          echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> config.properties
          echo FIREBASE_SERVICE_ACCOUNT_JSON="${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" >> config.properties

      - name: Upload EXE + config
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            **/*.exe
            config.properties
